### ISSUE TITLE
RF settings description

### ISSUE THREAD

**Issue by dontsovcmc** [DzikuVx/QuadMeUp_Crossbow#28]
Can you write something about RF settings? It's very important for reliable, delay and radius.. Thanks

    uint32_t frequency = 867000000;
    uint32_t loraBandwidth = 250000;
    uint8_t loraSpreadingFactor = 7;
    uint8_t loraCodingRate = 6;

Why you don't change TxPower?

    LoRa.setTxPower(17); //2-17

Thanks!

**Comment by DzikuVx** [comment]
Those value seems to be working pretty well. It's a compromise between range and delay. At 25mW (14dBm) I was able to test at 3km range on the ground with few dB of budget link still to spare. At few meters above the ground.

For the second question, default is 50mW (17dBm) at it is the strongest allowed output power for SX1276 without duty cycle limitation

**Comment by DzikuVx** [comment]
Let's say solved in 8ffaccbd5fdc0b2bb4a06b334f99e6f50e6e6bbb
