### ISSUE TITLE
Which libraries do you use?

### ISSUE THREAD

**Issue by unitware** [DzikuVx/QuadMeUp_Crossbow#45]
I'm trying to locate correct sources and versions of all libraries but I'm not sure I got it correct. It would be great if you could help me out, maybe update the readme?

My PPMReader (https://github.com/Nikkilae/PPM-reader) does not match the function prototype
"
crossbow:38: error: no matching function for call to 'PPMReader::PPMReader(int, int, bool)'
 PPMReader ppmReader(PPM_INPUT_PIN, PPM_INPUT_INTERRUPT, true);
"

Then I need to fix the InterruptHandler to support the M0 chip but thats another story :)

**Comment by unitware** [comment]
ok, I was using the wrong lib, Just found your https://github.com/DzikuVx/PPMReader which I assume is the correct one. But then I realized that you are using sbus from your transceiver..

I have also found:
https://github.com/adafruit/Adafruit_SSD1306
https://github.com/adafruit/Adafruit-GFX-Library

which seems to work.

**Comment by unitware** [comment]
Have you used the PPMReader at the same time as the lora library? I am having trouble getting communications to run when I am instantiating the ppmReader, interrupt conflict?

**Comment by DzikuVx** [comment]
PPM reader is not longer used in current code. The only external lib would be Adafruit_SSD1306. Everything else is part of the project itself

**Comment by unitware** [comment]
Thanks, I'll try to get a PPM working then (I do not have sbus output)
